# Generated by Django 3.2 on 2021-04-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='opinion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
