# Generated by Django 3.2 on 2021-04-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bf',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.IntegerField(null=True),
        ),
    ]
